### PR TITLE
fix(`write-feed`): don't throw on conflicts

### LINKED ISSUE #38: Updating feed to the same reference fails
See https://github.com/ethersphere/swarm-actions/runs/5522154884?check_suite_focus=true
Screenshot 2022-03-12 at 16 57 59

### PR DESCRIPTION
**Pull request by filoozom**
Fixes #38

### CODE REVIEW

File: write-feed/src/main.ts [hunk 1]
```diff
@@ -29,12 +29,21 @@ const run = async ({
...
+    const writer = bee.makeFeedWriter('sequence', topic, signer)
+    const response = await writer.upload(postageBatchId, reference)
+    const manifest = await bee.createFeedManifest(postageBatchId, 'sequence', topic, signerToAddress(signer))
 
-  core.setOutput('reference', response)
-  core.setOutput('manifest', manifest)
+    core.setOutput('reference', response)
+    core.setOutput('manifest', manifest)
+  } catch (err) {
+    if (err instanceof BeeResponseError && err.status === 409) {
```
Comment (vojtechsimetka) [inline write-feed/src/main.ts:40]: @AuHau is this sufficient condition? I remember we had issues with “instanceof” checks in past.

Comment (filoozom) [reply write-feed/src/main.ts:40]: As an example (not the same endpoint, but should be basically the same without the validation):

```js
const { Bee, BeeResponseError } = require('@ethersphere/bee-js')
const bee = new Bee('https://httpstat.us/409')

;(async () => {
	try {
		await bee.pin(Array.from({ length: 64 }).map(i => 0).join(''))
	}
	catch (err) {
		console.assert(err instanceof BeeResponseError, 'err instanceof BeeResponseError')
	}

 	console.assert(!(new Error() instanceof BeeResponseError), '!(new Error() instanceof BeeResponseError)')
})()

```

Comment (vojtechsimetka) [reply write-feed/src/main.ts:40]: Yes but we used to have a problem where any Error was instanceof BeeError. This is due to some nodejs inheritance bug. I wanted to test this in the github action environment.

Comment (vojtechsimetka) [reply write-feed/src/main.ts:40]: See https://github.com/ethersphere/bee-js/issues/204 but looks like it may be solved (we no linger use webpack for nodejs builds).

Comment (filoozom) [reply write-feed/src/main.ts:40]: I added an assert for `new Error instanceof BeeResponseError` which seems to work, but sure, probably best to wait for Adam. Looks like it's also used in `bee-js` directly: https://github.com/ethersphere/bee-js/blob/88039bb5f86e6cf528a9572e92d0146f398b3fb3/test/utils.ts#L291.

Comment (AuHau) [reply write-feed/src/main.ts:40]: It should be safe to use in this context. 

The mentioned problem was related to NodeJS modules and especially thrown `TypeErrors` from NodeJS modules that is not the case here. 

Good point @vojtechsimetka that it might not even be in the scope anymore since we dropped webpack nodejs builds. I should re-investigate later on.

**Review by AuHau — APPROVED** [review]
LGTM
